export const BACKUP_ADDED = "BACKUP_ADDED"
export const BACKUP_RENAMED = "BACKUP_RENAMED"
export const BACKUP_REMOVED = "BACKUP_REMOVED"

export const STATE_SUBSCRIPTION_UPDATED = "STATE_SUBSCRIPTION_UPDATED"
