compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules
# allow NPM_TOKEN env to be set, but provide '' as fallback. This allows CI to publish packages, but not require env var.
# See https://yarnpkg.com/configuration/yarnrc
npmAuthToken: "${NPM_TOKEN-}"

npmPublishAccess: public

yarnPath: .yarn/releases/yarn-4.1.1.cjs

# Ignore specific warnings
logFilters:
  - code: YN0057 # Resolutions field will be ignored
    level: discard
  - code: YN0060 # Peer dependency issues
    level: discard
  - code: YN0086 # Some peer dependencies are incorrectly met
    level: discard
