export default {
  STARTUP: Symbol('STARTUP'), // symbols are supported if that's how you roll
  TEMPERATURE_REQUEST: 'TEMPERATURE_REQUEST',
  TEMPERATURE_RECEIVE: 'TEMPERATURE_RECEIVE',
  TEMPERATURE_FAILURE: 'TEMPERATURE_FAILURE'
}
