export const BACKUP_ADDED = "BACKUP_ADDED"
export const BACKUP_RENAMED = "BACKUP_RENAMED"

export const COMMAND_ADDED = "COMMAND_ADDED"

export const CONNECTION_ESTABLISHED = "CONNECTION_ESTABLISHED"
export const CONNECTION_DISCONNECTED = "CONNECTION_DISCONNECTED"

export const EXECUTED_COMMAND_ADDED = "EXECUTED_COMMAND_ADDED"
