export const CONNECTION_ESTABLISHED = "CONNECTION_ESTABLISHED"
export const CONNECTION_DISCONNECTED = "CONNECTION_DISCONNECTED"

export const COMMAND_ADDED = "COMMAND_ADDED"

export const EXECUTED_COMMAND_ADDED = "EXECUTED_COMMAND_ADDED"
